# Generated by Django 5.1.5 on 2025-02-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
